version: '3'

services:
  gateway:
    container_name: gateway
    restart: always
    build: ./gateway
    ports:
      - "4000:4000"

  characters:
    container_name: characters
    restart: always
    build: ./characters
    ports:
      - "4001:4001"

  films:
    container_name: films
    restart: always
    build: ./films
    ports:
      - "4002:4002"

  planets:
    container_name: planets
    restart: always
    build: ./planets
    ports:
      - "4003:4003"

  data:
    container_name: data
    restart: always
    build: ./data
    ports:
      - "4004:4004"